# Build de Angular
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# Imagen final: Nginx sirviendo el build de Angular
FROM nginx:1.27-alpine
COPY docker/nginx.docker.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/sistema-escolar-frontend/browser /usr/share/nginx/html
EXPOSE 80
